// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Study.Persistence;

#nullable disable

namespace Study.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    [Migration("20260626121855_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("study")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Study.Domain.Entities.CardProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Difficulty")
                        .HasColumnType("float");

                    b.Property<int>("Lapses")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextReviewDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<double>("Stability")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("UserId", "CardId");

                    b.HasIndex("UserId", "NextReviewDate");

                    b.HasIndex("UserId", "TargetLanguage");

                    b.ToTable("card_progress", "study");
                });

            modelBuilder.Entity("Study.Domain.Entities.UserStatistics", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("LearnedCards")
                        .HasColumnType("int");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("ReviewedCards")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("user_statistics", "study");
                });
#pragma warning restore 612, 618
        }
    }
}
